name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    # COMMON

    - uses: actions/checkout@v2

    # COMPOSER

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: PHP Lint
    # uses: michaelw90/PHP-Lint@master
      uses: awanesia/PHP-Lint@master

    # MISSPELL

    # uses: sobolevn/misspell-fixer-action@master
    # Use unreleased dev version while we wait for a new one to be cut. See:
    # https://github.com/sobolevn/misspell-fixer-action/issues/15
    - uses: sobolevn/misspell-fixer-action@8842a5615f83fed75e8a87015e9300a54d049961
      with:
        options: '-rsvn .'
    - uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'Fixes by misspell-fixer'
        title: 'Typos fix by misspell-fixer'

    
